name: onboarding_concept
description: "Flutter Design Challenges: Onboarding Concept"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^5.3.2
  equatable: ^2.0.5
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.4.1
  get: ^4.6.5
  get_it: ^7.6.0
  intl: ^0.18.1
  ionicons: ^0.2.2
  json_annotation: ^4.8.1
  lint: ^1.5.3
  loading_animation_widget: ^1.2.0+4
  logger: ^2.0.1
  quickalert: ^1.0.1
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8

flutter:
  uses-material-design: true
  assets:
    - lib/ui/utils/assets/images/
